<<<<<<< HEAD
services:
  - type: web
    name: mini-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
=======
services:
  - type: web
    name: mini-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
>>>>>>> c179f208c448770023f8661d83f453184a65cddd
    startCommand: gunicorn main:app